In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
 
%matplotlib inline
 
import warnings
warnings.filterwarnings('ignore')

In [5]:
train = pd.read_csv('Train.csv')
test = pd.read_csv('Test.csv')

In [6]:
train.head()

Applicant_ID  form_field1  form_field2  form_field3  form_field4  \
0  Apcnt_1000000       3436.0      0.28505       1.6560          0.0   
1  Apcnt_1000004       3456.0      0.67400       0.2342          0.0   
2  Apcnt_1000008       3276.0      0.53845       3.1510          0.0   
3  Apcnt_1000012       3372.0      0.17005       0.5050          0.0   
4  Apcnt_1000016       3370.0      0.77270       1.1010          0.0   

   form_field5  form_field6  form_field7  form_field8  form_field9  ...  \
0        0.000          0.0   10689720.0     252072.0    4272776.0  ...   
1        0.000          0.0     898979.0     497531.0    9073814.0  ...   
2        6.282          NaN     956940.0          NaN     192944.0  ...   
3        0.000     192166.0    3044703.0     385499.0    3986472.0  ...   
4        0.000       1556.0     214728.0     214728.0    1284089.0  ...   

   form_field42  form_field43  form_field44  form_field45  form_field46  \
0      0.392854          2.02      0.711632           0.0           0.0   
1      0.314281          8.08      0.183584           NaN           0.0   
2      0.162965         18.18      0.791136           0.0           0.0   
3      0.488884          2.02      0.685168           NaN           0.0   
4      0.275000         12.12      0.438168           0.0           0.0   

   form_field47  form_field48  form_field49  form_field50  default_status  
0        charge           NaN      1.129518      0.044335              no  
1        charge    349.805730      1.620483      0.322436              no  
2        charge           NaN      1.513370      0.011640             yes  
3        charge     89.940100      0.664452      0.082729              no  
4        charge     97.887502      1.427891      0.045630              no  

[5 rows x 52 columns]

In [7]:
train['form_field4'].unique()

array([ 0.    ,  8.3718,  4.9068, ...,  2.9196, 12.2796, 23.355 ])

In [8]:
train.shape

(56000, 52)

In [9]:
train[['form_field19']]

form_field19
0               3.0
1               2.0
2               0.0
3               1.0
4               3.0
...             ...
55995           0.0
55996           0.0
55997           2.0
55998           0.0
55999           3.0

[56000 rows x 1 columns]

In [10]:
train[['form_field20']]

form_field20
0               3.0
1               2.0
2               0.0
3               1.0
4               3.0
...             ...
55995           0.0
55996           1.0
55997           2.0
55998           0.0
55999           3.0

[56000 rows x 1 columns]

In [11]:
train['form_field19'].unique()

array([ 3.,  2.,  0.,  1.,  6.,  7., 12.,  4.,  5.,  9.,  8., 15., 11.,
       20., 10., 14., 13., 17., 16., 22., 18., 28., 19., 24., 21., 25.,
       nan])

In [12]:
train['form_field20'].unique()

array([ 3.,  2.,  0.,  1.,  6.,  7., 12.,  4.,  5.,  8., nan,  9., 15.,
       11., 20., 10., 14., 13., 16., 17., 22., 18., 29., 19., 24., 21.,
       25., 28.])

In [13]:
train.columns

Index(['Applicant_ID', 'form_field1', 'form_field2', 'form_field3',
       'form_field4', 'form_field5', 'form_field6', 'form_field7',
       'form_field8', 'form_field9', 'form_field10', 'form_field11',
       'form_field12', 'form_field13', 'form_field14', 'form_field15',
       'form_field16', 'form_field17', 'form_field18', 'form_field19',
       'form_field20', 'form_field21', 'form_field22', 'form_field23',
       'form_field24', 'form_field25', 'form_field26', 'form_field27',
       'form_field28', 'form_field29', 'form_field30', 'form_field31',
       'form_field32', 'form_field33', 'form_field34', 'form_field35',
       'form_field36', 'form_field37', 'form_field38', 'form_field39',
       'form_field40', 'form_field41', 'form_field42', 'form_field43',
       'form_field44', 'form_field45', 'form_field46', 'form_field47',
       'form_field48', 'form_field49', 'form_field50', 'default_status'],
      dtype='object')

In [14]:
train.head()

Applicant_ID  form_field1  form_field2  form_field3  form_field4  \
0  Apcnt_1000000       3436.0      0.28505       1.6560          0.0   
1  Apcnt_1000004       3456.0      0.67400       0.2342          0.0   
2  Apcnt_1000008       3276.0      0.53845       3.1510          0.0   
3  Apcnt_1000012       3372.0      0.17005       0.5050          0.0   
4  Apcnt_1000016       3370.0      0.77270       1.1010          0.0   

   form_field5  form_field6  form_field7  form_field8  form_field9  ...  \
0        0.000          0.0   10689720.0     252072.0    4272776.0  ...   
1        0.000          0.0     898979.0     497531.0    9073814.0  ...   
2        6.282          NaN     956940.0          NaN     192944.0  ...   
3        0.000     192166.0    3044703.0     385499.0    3986472.0  ...   
4        0.000       1556.0     214728.0     214728.0    1284089.0  ...   

   form_field42  form_field43  form_field44  form_field45  form_field46  \
0      0.392854          2.02      0.711632           0.0           0.0   
1      0.314281          8.08      0.183584           NaN           0.0   
2      0.162965         18.18      0.791136           0.0           0.0   
3      0.488884          2.02      0.685168           NaN           0.0   
4      0.275000         12.12      0.438168           0.0           0.0   

   form_field47  form_field48  form_field49  form_field50  default_status  
0        charge           NaN      1.129518      0.044335              no  
1        charge    349.805730      1.620483      0.322436              no  
2        charge           NaN      1.513370      0.011640             yes  
3        charge     89.940100      0.664452      0.082729              no  
4        charge     97.887502      1.427891      0.045630              no  

[5 rows x 52 columns]

In [15]:
train.columns

Index(['Applicant_ID', 'form_field1', 'form_field2', 'form_field3',
       'form_field4', 'form_field5', 'form_field6', 'form_field7',
       'form_field8', 'form_field9', 'form_field10', 'form_field11',
       'form_field12', 'form_field13', 'form_field14', 'form_field15',
       'form_field16', 'form_field17', 'form_field18', 'form_field19',
       'form_field20', 'form_field21', 'form_field22', 'form_field23',
       'form_field24', 'form_field25', 'form_field26', 'form_field27',
       'form_field28', 'form_field29', 'form_field30', 'form_field31',
       'form_field32', 'form_field33', 'form_field34', 'form_field35',
       'form_field36', 'form_field37', 'form_field38', 'form_field39',
       'form_field40', 'form_field41', 'form_field42', 'form_field43',
       'form_field44', 'form_field45', 'form_field46', 'form_field47',
       'form_field48', 'form_field49', 'form_field50', 'default_status'],
      dtype='object')

In [16]:
test.columns

Index(['Applicant_ID', 'form_field1', 'form_field2', 'form_field3',
       'form_field4', 'form_field5', 'form_field6', 'form_field7',
       'form_field8', 'form_field9', 'form_field10', 'form_field11',
       'form_field12', 'form_field13', 'form_field14', 'form_field15',
       'form_field16', 'form_field17', 'form_field18', 'form_field19',
       'form_field20', 'form_field21', 'form_field22', 'form_field23',
       'form_field24', 'form_field25', 'form_field26', 'form_field27',
       'form_field28', 'form_field29', 'form_field30', 'form_field31',
       'form_field32', 'form_field33', 'form_field34', 'form_field35',
       'form_field36', 'form_field37', 'form_field38', 'form_field39',
       'form_field40', 'form_field41', 'form_field42', 'form_field43',
       'form_field44', 'form_field45', 'form_field46', 'form_field47',
       'form_field48', 'form_field49', 'form_field50'],
      dtype='object')

In [17]:
train['form_field17'].unique()

array([ 1., nan,  0.,  6.,  8.,  2.,  3.,  7.,  5.,  4.,  9., 11., 13.,
       10., 21., 16.])

In [18]:
train['form_field18'].unique()

array([ 1., nan,  0.,  6.,  8.,  3.,  2.,  7.,  5.,  4.,  9., 11., 13.,
       10., 12., 21., 16.])

In [19]:
train.columns

Index(['Applicant_ID', 'form_field1', 'form_field2', 'form_field3',
       'form_field4', 'form_field5', 'form_field6', 'form_field7',
       'form_field8', 'form_field9', 'form_field10', 'form_field11',
       'form_field12', 'form_field13', 'form_field14', 'form_field15',
       'form_field16', 'form_field17', 'form_field18', 'form_field19',
       'form_field20', 'form_field21', 'form_field22', 'form_field23',
       'form_field24', 'form_field25', 'form_field26', 'form_field27',
       'form_field28', 'form_field29', 'form_field30', 'form_field31',
       'form_field32', 'form_field33', 'form_field34', 'form_field35',
       'form_field36', 'form_field37', 'form_field38', 'form_field39',
       'form_field40', 'form_field41', 'form_field42', 'form_field43',
       'form_field44', 'form_field45', 'form_field46', 'form_field47',
       'form_field48', 'form_field49', 'form_field50', 'default_status'],
      dtype='object')

In [20]:
train.isnull().sum()

Applicant_ID          0
form_field1        2529
form_field2        3844
form_field3         355
form_field4         355
form_field5         355
form_field6       13360
form_field7        5163
form_field8       13360
form_field9        8008
form_field10        355
form_field11      31421
form_field12       9895
form_field13       5889
form_field14          0
form_field15      22475
form_field16      13036
form_field17      11151
form_field18      10402
form_field19          4
form_field20        355
form_field21      15854
form_field22      20400
form_field23      28123
form_field24      13297
form_field25       5450
form_field26       7438
form_field27       9299
form_field28        355
form_field29        355
form_field30      25509
form_field31      39408
form_field32       5450
form_field33       1256
form_field34        355
form_field35      23148
form_field36       1995
form_field37       5450
form_field38        355
form_field39       4211
form_field40      43729
form_field41    

In [21]:
test.isnull().sum()

Applicant_ID        0
form_field1      1110
form_field2      1709
form_field3       146
form_field4       146
form_field5       146
form_field6      5604
form_field7      2231
form_field8      5604
form_field9      3400
form_field10      147
form_field11    13398
form_field12     4183
form_field13     2463
form_field14        0
form_field15     9592
form_field16     5474
form_field17     4695
form_field18     4369
form_field19        0
form_field20      147
form_field21     6707
form_field22     8724
form_field23    12125
form_field24     5605
form_field25     2256
form_field26     3172
form_field27     3910
form_field28      147
form_field29      147
form_field30    10908
form_field31    16810
form_field32     2256
form_field33      495
form_field34      147
form_field35     9866
form_field36      903
form_field37     2256
form_field38      147
form_field39     1829
form_field40    18828
form_field41    16349
form_field42      578
form_field43      250
form_field44     2362
form_field

In [22]:
train.shape

(56000, 52)

In [23]:
test.shape

(24000, 51)

In [24]:
#train.drop(['form_field11', 'form_field31', 'form_field40', 'form_field41', 'form_field45'], axis = 1, inplace = True)
#test.drop(['form_field11', 'form_field31', 'form_field40', 'form_field41', 'form_field45'], axis = 1, inplace = True)

In [25]:
train.shape, test.shape

((56000, 52), (24000, 51))

In [26]:
from sklearn.metrics import roc_auc_score
from catboost import CatBoostClassifier
import xgboost as xgb
from xgboost.sklearn import XGBClassifier

In [27]:
dict_ = {'charge': 1,
         'lending': 0}

target_map = {
    'yes': 1,
    'no': 0}

train.default_status.replace(target_map, inplace = True)

train['form_field47'].replace(dict_, inplace = True)
test['form_field47'].replace(dict_, inplace = True)

In [28]:
len(train.columns)

52

In [29]:
features = train.select_dtypes(exclude = object).columns.drop(['default_status'])

In [30]:
for col in features:
    train[col].fillna(-999, inplace = True)
    test[col].fillna(-999, inplace = True)

In [31]:
len(train.columns)

52

In [32]:
X = train[features]
y = train['default_status']

In [33]:
from sklearn.model_selection import StratifiedKFold

In [34]:
def metric(y, pred):
    return roc_auc_score(y, pred, labels=[0, 1])

In [35]:
# Specify number of folds
n_skf = 10
kf = StratifiedKFold(n_skf)


seed = 2020

## Manually tweak the hyperparameter, learning rate and n_estimators especially
params = {
    'n_estimators': 4000,
    'learning_rate': 0.01,
    'objective': 'CrossEntropy',
      'eval_metric':'AUC',
    'random_seed': seed,
    'early_stopping_rounds': 200,
    'use_best_model': True,
    'max_depth' : 8
}

In [36]:
for i, (tr_idx, vr_idx) in enumerate(kf.split(X,y)):
    print(tr_idx)

[ 5541  5542  5543 ... 55997 55998 55999]
[    0     1     2 ... 55997 55998 55999]
[    0     1     2 ... 55997 55998 55999]
[    0     1     2 ... 55997 55998 55999]
[    0     1     2 ... 55997 55998 55999]
[    0     1     2 ... 55997 55998 55999]
[    0     1     2 ... 55997 55998 55999]
[    0     1     2 ... 55997 55998 55999]
[    0     1     2 ... 55997 55998 55999]
[    0     1     2 ... 50515 50518 50519]


In [37]:
score_list = []
score = 0
test_oofs = []

for i, (tr_idx, vr_idx) in enumerate(kf.split(X, y)):
    
    xtrain, ytrain = X.loc[tr_idx, features], y.loc[tr_idx]
    xval, yval = X.loc[vr_idx, features], y.loc[vr_idx]

    model = CatBoostClassifier(**params)
    model.fit(xtrain, ytrain, eval_set=[(xval,yval)], verbose=100)
    
    p = model.predict_proba(xval)[:, 1]
    sc = metric(yval, p)
    score_list.append(sc)
    score += sc/n_skf
    
    pred = model.predict_proba(test[features])[:, 1]
    test_oofs.append(pred)

    print('Fold {} : {}'.format(i, sc))

print()
print()
print('Avg log : ', score)

0:	test: 0.7918478	best: 0.7918478 (0)	total: 2.62s	remaining: 2h 54m 55s
100:	test: 0.8199874	best: 0.8199874 (100)	total: 13.1s	remaining: 8m 27s
200:	test: 0.8231007	best: 0.8231007 (200)	total: 22.7s	remaining: 7m 8s
300:	test: 0.8253684	best: 0.8253684 (300)	total: 32.4s	remaining: 6m 38s
400:	test: 0.8267275	best: 0.8267275 (400)	total: 44.5s	remaining: 6m 39s
500:	test: 0.8279217	best: 0.8279251 (499)	total: 55.1s	remaining: 6m 24s
600:	test: 0.8287035	best: 0.8287035 (600)	total: 1m 5s	remaining: 6m 10s
700:	test: 0.8294019	best: 0.8294022 (699)	total: 1m 16s	remaining: 6m
800:	test: 0.8298826	best: 0.8299048 (790)	total: 1m 28s	remaining: 5m 51s
900:	test: 0.8302504	best: 0.8302810 (893)	total: 1m 39s	remaining: 5m 43s
1000:	test: 0.8307849	best: 0.8307896 (997)	total: 1m 51s	remaining: 5m 35s
1100:	test: 0.8310547	best: 0.8310804 (1068)	total: 2m 2s	remaining: 5m 23s
1200:	test: 0.8311840	best: 0.8311896 (1183)	total: 2m 13s	remaining: 5m 11s
1300:	test: 0.8315276	best: 0.831

2400:	test: 0.8441662	best: 0.8444773 (2251)	total: 3m 36s	remaining: 2m 24s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.8444773411
bestIteration = 2251

Shrink model to first 2252 iterations.
Fold 4 : 0.8444773410781277
0:	test: 0.8026219	best: 0.8026219 (0)	total: 147ms	remaining: 9m 46s
100:	test: 0.8302852	best: 0.8302852 (100)	total: 11.6s	remaining: 7m 29s
200:	test: 0.8342721	best: 0.8342721 (200)	total: 22s	remaining: 6m 56s
300:	test: 0.8364720	best: 0.8364735 (299)	total: 32.8s	remaining: 6m 43s
400:	test: 0.8379418	best: 0.8379418 (400)	total: 43.6s	remaining: 6m 31s
500:	test: 0.8392902	best: 0.8392902 (500)	total: 54.6s	remaining: 6m 21s
600:	test: 0.8400884	best: 0.8400884 (600)	total: 1m 6s	remaining: 6m 15s
700:	test: 0.8407767	best: 0.8407803 (695)	total: 1m 17s	remaining: 6m 3s
800:	test: 0.8411782	best: 0.8411782 (800)	total: 1m 28s	remaining: 5m 51s
900:	test: 0.8415969	best: 0.8415969 (900)	total: 1m 38s	remaining: 5m 39s
1000:	test: 0.8417

1500:	test: 0.8467257	best: 0.8467257 (1500)	total: 2m 30s	remaining: 4m 11s
1600:	test: 0.8467648	best: 0.8467983 (1545)	total: 2m 40s	remaining: 4m
1700:	test: 0.8468038	best: 0.8468447 (1685)	total: 2m 49s	remaining: 3m 49s
1800:	test: 0.8468345	best: 0.8468753 (1732)	total: 2m 58s	remaining: 3m 38s
1900:	test: 0.8468846	best: 0.8468914 (1885)	total: 3m 7s	remaining: 3m 27s
2000:	test: 0.8470482	best: 0.8470482 (2000)	total: 3m 16s	remaining: 3m 16s
2100:	test: 0.8471410	best: 0.8471768 (2073)	total: 3m 25s	remaining: 3m 5s
2200:	test: 0.8472737	best: 0.8472872 (2192)	total: 3m 33s	remaining: 2m 54s
2300:	test: 0.8473110	best: 0.8473492 (2275)	total: 3m 42s	remaining: 2m 44s
2400:	test: 0.8472894	best: 0.8473579 (2382)	total: 3m 53s	remaining: 2m 35s
2500:	test: 0.8473556	best: 0.8473782 (2472)	total: 4m 4s	remaining: 2m 26s
2600:	test: 0.8473601	best: 0.8474070 (2555)	total: 4m 15s	remaining: 2m 17s
2700:	test: 0.8473729	best: 0.8474070 (2555)	total: 4m 26s	remaining: 2m 7s
2800:	t

In [38]:
f"{n_skf} fold CV, score: {score}" #Increase in local cv score should probably lead to increase in Leaderboard score

'10 fold CV, score: 0.8414054931153483'

In [64]:
test_oofs

[array([0.30213343, 0.44499827, 0.36296384, ..., 0.28552438, 0.52739302,
        0.20275127]),
 array([0.32063421, 0.37933625, 0.3630792 , ..., 0.2955752 , 0.53483498,
        0.2013389 ]),
 array([0.29860268, 0.38757586, 0.38794724, ..., 0.26819952, 0.54545963,
        0.19546488]),
 array([0.31203107, 0.40635114, 0.39923915, ..., 0.29784221, 0.5311733 ,
        0.21009279]),
 array([0.30896848, 0.42498909, 0.41508828, ..., 0.29022784, 0.58612385,
        0.17620641]),
 array([0.33816013, 0.39662144, 0.41011058, ..., 0.30062129, 0.54162048,
        0.18586841]),
 array([0.30459496, 0.37344413, 0.41264472, ..., 0.26957679, 0.55018178,
        0.19065253]),
 array([0.28446716, 0.38993754, 0.39537534, ..., 0.28520926, 0.57344157,
        0.1902729 ]),
 array([0.28114073, 0.41998273, 0.33415397, ..., 0.28112709, 0.51988342,
        0.20409841]),
 array([0.32420354, 0.33403801, 0.35762793, ..., 0.27219364, 0.55482573,
        0.21140756])]

In [65]:
oof_prediction = pd.DataFrame(test_oofs).T

In [66]:
oof_prediction.head()

0         1         2         3         4         5         6  \
0  0.302133  0.320634  0.298603  0.312031  0.308968  0.338160  0.304595   
1  0.444998  0.379336  0.387576  0.406351  0.424989  0.396621  0.373444   
2  0.362964  0.363079  0.387947  0.399239  0.415088  0.410111  0.412645   
3  0.731142  0.739864  0.742441  0.761255  0.735113  0.746385  0.750472   
4  0.167206  0.170846  0.163419  0.164726  0.165254  0.148719  0.174102   

          7         8         9  
0  0.284467  0.281141  0.324204  
1  0.389938  0.419983  0.334038  
2  0.395375  0.334154  0.357628  
3  0.754447  0.735403  0.719562  
4  0.154023  0.176723  0.131201

In [67]:
type(test_oofs)

list

In [68]:
test_oofs[:5]

[array([0.30213343, 0.44499827, 0.36296384, ..., 0.28552438, 0.52739302,
        0.20275127]),
 array([0.32063421, 0.37933625, 0.3630792 , ..., 0.2955752 , 0.53483498,
        0.2013389 ]),
 array([0.29860268, 0.38757586, 0.38794724, ..., 0.26819952, 0.54545963,
        0.19546488]),
 array([0.31203107, 0.40635114, 0.39923915, ..., 0.29784221, 0.5311733 ,
        0.21009279]),
 array([0.30896848, 0.42498909, 0.41508828, ..., 0.29022784, 0.58612385,
        0.17620641])]

In [69]:
oof_prediction.head()

0         1         2         3         4         5         6  \
0  0.302133  0.320634  0.298603  0.312031  0.308968  0.338160  0.304595   
1  0.444998  0.379336  0.387576  0.406351  0.424989  0.396621  0.373444   
2  0.362964  0.363079  0.387947  0.399239  0.415088  0.410111  0.412645   
3  0.731142  0.739864  0.742441  0.761255  0.735113  0.746385  0.750472   
4  0.167206  0.170846  0.163419  0.164726  0.165254  0.148719  0.174102   

          7         8         9  
0  0.284467  0.281141  0.324204  
1  0.389938  0.419983  0.334038  
2  0.395375  0.334154  0.357628  
3  0.754447  0.735403  0.719562  
4  0.154023  0.176723  0.131201

In [70]:
oof_prediction.columns = ['fold_'+ str(i) for i in range(1, n_skf + 1)]

In [71]:
oof_prediction.head()

fold_1    fold_2    fold_3    fold_4    fold_5    fold_6    fold_7  \
0  0.302133  0.320634  0.298603  0.312031  0.308968  0.338160  0.304595   
1  0.444998  0.379336  0.387576  0.406351  0.424989  0.396621  0.373444   
2  0.362964  0.363079  0.387947  0.399239  0.415088  0.410111  0.412645   
3  0.731142  0.739864  0.742441  0.761255  0.735113  0.746385  0.750472   
4  0.167206  0.170846  0.163419  0.164726  0.165254  0.148719  0.174102   

     fold_8    fold_9   fold_10  
0  0.284467  0.281141  0.324204  
1  0.389938  0.419983  0.334038  
2  0.395375  0.334154  0.357628  
3  0.754447  0.735403  0.719562  
4  0.154023  0.176723  0.131201

In [72]:
oof_prediction.shape

(24000, 10)

In [73]:
sub = pd.read_csv('SampleSubmission.csv')

In [74]:
### We take the mean of all row predictions to generate submission
sub['default_status'] = np.mean(test_oofs, axis = 0) 

In [75]:
sub.to_csv('2nd_sub.csv', index = False)

Dropping some columns with more null values

In [ ]:
train.drop(['form_field11', 'form_field31', 'form_field40', 'form_field41', 'form_field45'], axis = 1, inplace = True)
test.drop(['form_field11', 'form_field31', 'form_field40', 'form_field41', 'form_field45'], axis = 1, inplace = True)

In [1]:
features = train.select_dtypes(exclude = object).columns.drop(['default_status'])

NameError: name 'train' is not defined

In [2]:
for col in features:
    train[col].fillna(-999, inplace = True)
    test[col].fillna(-999, inplace = True)

NameError: name 'features' is not defined

In [3]:
X = train[features]
y = train['default_status']

NameError: name 'train' is not defined

In [ ]:
from sklearn.model_selection import StratifiedKFold

def metric(y, pred):
    return roc_auc_score(y, pred, labels=[0, 1])

# Specify number of folds
n_skf = 10
kf = StratifiedKFold(n_skf)


seed = 2020

## Manually tweak the hyperparameter, learning rate and n_estimators especially
params = {
    'n_estimators': 4000,
    'learning_rate': 0.01,
    'objective': 'CrossEntropy',
      'eval_metric':'AUC',
    'random_seed': seed,
    'early_stopping_rounds': 200,
    'use_best_model': True,
    'max_depth' : 8
}

for i, (tr_idx, vr_idx) in enumerate(kf.split(X,y)):
    print(tr_idx)



score_list = []
score = 0
test_oofs = []

for i, (tr_idx, vr_idx) in enumerate(kf.split(X, y)):
    
    xtrain, ytrain = X.loc[tr_idx, features], y.loc[tr_idx]
    xval, yval = X.loc[vr_idx, features], y.loc[vr_idx]

    model = CatBoostClassifier(**params)
    model.fit(xtrain, ytrain, eval_set=[(xval,yval)], verbose=100)
    
    p = model.predict_proba(xval)[:, 1]
    sc = metric(yval, p)
    score_list.append(sc)
    score += sc/n_skf
    
    pred = model.predict_proba(test[features])[:, 1]
    test_oofs.append(pred)

    print('Fold {} : {}'.format(i, sc))

print()
print()
print('Avg log : ', score)

f"{n_skf} fold CV, score: {score}" #Increase in local cv score should probably lead to increase in Leaderboard score